### ISSUE TITLE
[ebuild request] vkquake2

### ISSUE THREAD

**Issue by mrturcot** [GoGoOtaku/GoGoOverlay#1]
Hey I just wanna say thanks so much for the vkquake ebuild you rock! I just wanted to ask is there any chance you would want to make one for vkquake2? https://github.com/kondrak/vkQuake2

Just wondering no biggie, thanks so much! Best regards!

**Comment by GoGoOtaku** [comment]
I added vkQuake2.

Sadly Quake II (and vkQuake2 is heavily based on the original code) requires a rather strict folder structure which only could be resolved by heavy rewrites to how the engine loads content. I tried to make alternative ways work but gave up in the end as they weren't working.

The way to use it right now is running vkq2-link that comes with this package inside your game folder. It will symlink every library and executable so that updates will still apply to your local game.
I hope this isn't too much of a bother.

**Comment by mrturcot** [comment]
Wow thank you!! You rock :)

**Comment by mrturcot** [comment]
Hey, just FYI "vkq2-link" worked great :) However after executing "quake2" I had this error

```
LoadLibrary("ref_vk.so") failed: /usr/bin/ref_vk.so: cannot open shared object file: No such file or directory
Only Vulkan renderer is supported on Linux.
```

So I just ran "ln -s /usr/share/vkquake2/ref_vk.so /usr/bin/ref_vk.so" and works fine after that. Im not sure if thats a proper way to solve the issue. Maybe you know more. Many thanks again, runs great!

**Comment by GoGoOtaku** [comment]
Hm. I'm looking into this

**Comment by GoGoOtaku** [comment]
So for me it works which doesn't help either of us to fix this.
So what I did:
* Installed it via `emerge vkQuake2` as root (the only step as root)
* Went into my game folder (in my case ~/Games/gog/quake-ii but that is probably a different folder for you)
* Ran `vkq2-link` to create sym-links
* Ran `./quake2`
* Alternatively I added it to Lutris (but steam does the same) and launched it through there

**Comment by mrturcot** [comment]
You're right it's working flawless, thanks again!

**Comment by mrturcot** [comment]
everything working great: CLOSED
